CREATE TABLE Users(
    ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Number VARCHAR(100) NOT NULL,
    Mail VARCHAR(100) NOT NULL,
    Password VARCHAR(100) NOT NULL,
    GSTIN VARCHAR(100) NOT NULL,
    -- Role BIT DEFAULT 0 NOT NULL,
    Created_at DATETIME NOT NULL
);